apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: a5020877/docker-fastapi:1ab06fd9e2e61cb1fb188c7709f5615f3514d3c1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
