apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: a5020877/docker-fastapi:203cf17ccf94b28933005705458c8eb0c1356f55
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
