apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: a5020877/docker-fastapi:389021278a3802062fbea2eabb60120a9fda59c2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
